name: CI
on:
  workflow_dispatch:
    inputs:
      ros_distro:
        description: 'Distro to build'
        type: choice
        options: [all, jazzy, kilted, lyrical, rolling]
        default: all
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]
  schedule:
    # Run every morning at 01:00 to detect flakiness and broken dependencies
    - cron: '0 1 * * *'
      timezone: "Europe/Zurich"

jobs:
  ci:
    uses: Duatic/ci-workflows/.github/workflows/ci_orchestrator.yml@v1
    with:
      ros_distro: ${{ inputs.ros_distro }}
      badge_gist_id: ca9e04f4b6ad286dc6ebc1fd2651d76b
    secrets: inherit

  changelog:
    if: github.event_name == 'pull_request'
    uses: Duatic/ci-workflows/.github/workflows/reusable_changelog_check.yml@v1

  release-check:
    if: github.event_name == 'pull_request'
    uses: Duatic/ci-workflows/.github/workflows/reusable_release_check.yml@v1

  title:
    if: github.event_name == 'pull_request'
    uses: Duatic/ci-workflows/.github/workflows/reusable_title_check.yml@v1
